# https://taskfile.dev/usage/
version: "3"
tasks:
  ## Setup
  ## create-vite templates https://github.com/vitejs/vite/tree/main/packages/create-vite
  mk-vanilla-ts: bun create vite --template vanilla-ts vanilla-ts
  mk-react-ts: bun create vite --template react-ts react-ts
  mk-vue-ts: bun create vite --template vue-ts vue-ts
  mk-tailwind-react-ts: bun create vite tailwind-react-ts --template vanilla-ts
  mk-tailwind: bun create vite tailwind --template react-ts
